# Generated by Django 5.1.4 on 2025-01-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('picking_up', 'Đang đón khách'), ('ongoing', 'Đang di chuyển'), ('completed', 'Hoàn thành'), ('canceled', 'Hủy')], default='ongoing', max_length=10)),
                ('price', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app_admin.driver')),
                ('students', models.ManyToManyField(related_name='trips', to='app_admin.student')),
            ],
        ),
    ]
