# Generated by Django 5.1.4 on 2025-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_alter_driver_revenue_alter_student_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='my_wallet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='my_wallet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
